version: '3'
services:
  db:
    image: postgres
    volumes:
      - db-root:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    image: "mhutton86/rails-sidekiq-like-webapp:latest"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - webapp-logs:/myapp/log
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    volumes:
      - db-root:/var/lib/redis/data
  sidekiq:
    image: "mhutton86/rails-sidekiq-like-webapp:latest"
    command: 'bundle exec sidekiq'
    volumes:
      - webapp-logs:/myapp/log
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
    depends_on:
      - db
      - redis

volumes:
  db-root:
  webapp-logs:
