apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: db
    app: db
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
        app: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: password
        image: postgres
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: db-root
      restartPolicy: Always
      volumes:
      - name: db-root
        persistentVolumeClaim:
          claimName: db-root
status: {}
