apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
    app: db
  name: db
spec:
  ports:
  - name: "db-port"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: db
    app: db
status:
  loadBalancer: {}
