apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: sidekiq
    version: ${RAILS_APP_CONTAINER_VERSION}
  name: sidekiq
spec:
  selector:
    matchLabels:
      app: sidekiq
      version: ${RAILS_APP_CONTAINER_VERSION}
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sidekiq
        app: sidekiq
        version: ${RAILS_APP_CONTAINER_VERSION}
    spec:
      containers:
      - args:
        - bundle
        - exec
        - sidekiq
        env:
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)/12
        # RAILS_APP_CONTAINER_VERSION is replaced using envsubst in our K8 scripts
        name: sidekiq
        image: docker.pkg.github.com/mhutton86/fullstack-build-project/rails-sidekiq-like-webapp:${RAILS_APP_CONTAINER_VERSION}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /myapp/log
          name: webapp-logs
      restartPolicy: Always
      volumes:
      - name: webapp-logs
        persistentVolumeClaim:
          claimName: webapp-logs
      imagePullSecrets:
        - name: registry-secret
status: {}
