apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: sidekiq
  name: sidekiq
spec:
  selector:
    matchLabels:
      app: sidekiq
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sidekiq
        app: sidekiq
    spec:
      containers:
      - args:
        - bundle
        - exec
        - sidekiq
        env:
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)/12
        image: docker.pkg.github.com/mhutton86/fullstack-build-project/rails-sidekiq-like-webapp:1.0.0
        name: sidekiq
        resources: {}
        volumeMounts:
        - mountPath: /myapp/log
          name: webapp-logs
      restartPolicy: Always
      volumes:
      - name: webapp-logs
        persistentVolumeClaim:
          claimName: webapp-logs
      imagePullSecrets:
        - name: github-docker
status: {}
