apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
        app: webapp
    spec:
      containers:
      - args:
        - bundle
        - exec
        - rails
        - s
        - -p
        - "3000"
        - -b
        - 0.0.0.0
        env:
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://redis:6379/12
        image: docker.pkg.github.com/mhutton86/fullstack-build-project/rails-sidekiq-like-webapp:1.0.0
        name: web
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /myapp/log
          name: webapp-logs
      restartPolicy: Always
      volumes:
      - name: webapp-logs
        persistentVolumeClaim:
          claimName: webapp-logs
      imagePullSecrets:
        - name: github-docker
status: {}
