apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
    version: ${RAILS_APP_CONTAINER_VERSION}
  name: web
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        io.kompose.service: web
        app: webapp
        version: ${RAILS_APP_CONTAINER_VERSION}
    spec:
      containers:
      - args:
        - bundle
        - exec
        - rails
        - s
        - -p
        - "3000"
        - -b
        - 0.0.0.0
        env:
        - name: RAILS_ENV
          value: development
        - name: REDIS_URL
          value: redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)/12
        # RAILS_APP_CONTAINER_VERSION is replaced using envsubst in our K8 scripts
        name: web
        image: docker.pkg.github.com/mhutton86/fullstack-build-project/rails-sidekiq-like-webapp:${RAILS_APP_CONTAINER_VERSION}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /myapp/log
          name: webapp-logs
      restartPolicy: Always
      volumes:
      - name: webapp-logs
        persistentVolumeClaim:
          claimName: webapp-logs
      imagePullSecrets:
        - name: registry-secret
